version: '3.7'
services:
  golang:
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-80}"
    environment:
      - HTTP_PORT
      - DATABASE_URL=postgres://postgres:postgres@postgres/finch

  postgres:
    image: postgres:14.0-alpine
    restart: unless-stopped
    ports:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finch
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
